### ISSUE TITLE
Can I put more than one parameter for map_batch_parallel's item_mapper?

### ISSUE THREAD

**Issue by guotong1988** [YuriyGuts/pygoose#1]
Thank you.
@YuriyGuts

**Comment by YuriyGuts** [comment]
I'm not sure I understood the question, but if you'd like the mapper to return multiple values for the same argument, you can just return an array from the function like [this notebook does](https://github.com/YuriyGuts/kaggle-quora-question-pairs/blob/master/notebooks/feature-simple-summaries.ipynb). The mapper has to be a single function that takes a single item from a collection you're processing and returns a scalar or an array. If it has to accept multiple things as an input, I'd maybe make a list of n-tuples or a list of lists?

**Comment by guotong1988** [comment]
https://github.com/YuriyGuts/kaggle-quora-question-pairs/blob/master/notebooks/feature-tfidf.ipynb

put `vectorizer` as parameter

```
def compute_pair_distances(pair,vectorizer):
    q1_doc = ' '.join(pair[0])
    q2_doc = ' '.join(pair[1])
    
    pair_dtm = vectorizer.transform([q1_doc, q2_doc])
    q1_doc_vec = pair_dtm[0]
    q2_doc_vec = pair_dtm[1]
    
    return [
        cosine_distances(q1_doc_vec, q2_doc_vec)[0][0],
        euclidean_distances(q1_doc_vec, q2_doc_vec)[0][0],
    ]
```
